### ISSUE TITLE
Add User with a specific rank

### ISSUE THREAD

**Issue by elenalmg** [thomktz/betterave#6]
## Issue 

There are several users on Pampemousse

## Fix 
Add a rank to put different user :

1. student
2. student asso
3. teacher
4. admin

## Implementation
Add a User class in models
Add view for different users

**Comment by elenalmg** [comment]
branch : https://github.com/thomktz/betterave/tree/add_users

**Comment by elenalmg** [comment]
specific rank added  
faire attention aux cours, ce sont seulement les students qui doivent y avoir accès, donc à modifier dans la jointure avec class

il reste à faire les views pour chaque type d'utilisateurs

**Comment by thomktz** [comment]
> faire attention aux cours, ce sont seulement les students qui doivent y avoir accès, donc à modifier dans la jointure avec class

Tu veux dire quoi par y avoir accès ?
Et on peut juste laisser la liste des `class` vide pour les non étudiants (niveau 3 et 4) non?

**Comment by thomktz** [comment]
Lié mais peut être pour un autre PR: Ajouter un Modèle "Asso" -> Stocker membres bureau/com + logo + événements asso (Lesson?)

**Comment by elenalmg** [comment]
> > faire attention aux cours, ce sont seulement les students qui doivent y avoir accès, donc à modifier dans la jointure avec class
> 
> Tu veux dire quoi par y avoir accès ? Et on peut juste laisser la liste des `class` vide pour les non étudiants (niveau 3 et 4) non?

est ce que je fais une class "class_teacher" pour savoir ce que les teachers donnent comme cours ? ou on laisse dans classe ?

**Comment by elenalmg** [comment]
> > faire attention aux cours, ce sont seulement les students qui doivent y avoir accès, donc à modifier dans la jointure avec class
> 
> Tu veux dire quoi par y avoir accès ? Et on peut juste laisser la liste des `class` vide pour les non étudiants (niveau 3 et 4) non?

j'ai laissé les classes comme tu m'as conseillé, j'ai juste mis "participants" comme attribut de classe à la place de "students" pour que ça signife prof et élèves.
Pour les classes de profs, je mets seulement les cours dans lesquelles ils enseignent.

**Comment by thomktz** [comment]
Top, éventuellement faudra construire l'emploi du temps des profs à partir des Lessons et non des Class, pour les chargés de TD, etc
Mais bon à faire séparément, ça fait déjà un gros PR là!
